# Длины полей
NAME_MAX_LENGTH = 124
PROJECT_NAME_MAX_LENGTH = 200
ABOUT_MAX_LENGTH = 256
PHONE_MAX_LENGTH = 12
STATUS_MAX_LENGTH = 6

# Статусы проекта
STATUS_OPEN = 'open'
STATUS_CLOSED = 'closed'

# Пагинация
PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12

# Аватар
AVATAR_SIZE = 200
AVATAR_FONT_SIZE = 100
AVATAR_TEXT_COLOR = 'white'
AVATAR_FONT_PATH = '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'

# Цвета
COLOR_BLUE = '#5B8DEF'
COLOR_ORANGE = '#E8A838'
COLOR_GREEN = '#6BCB77'
COLOR_PURPLE = '#9B5DE5'
COLOR_PINK = '#F15BB5'
COLOR_CYAN = '#00BBF9'
COLOR_RED = '#FF6B6B'
COLOR_TEAL = '#4ECDC4'

AVATAR_COLORS = [
    COLOR_BLUE,
    COLOR_ORANGE,
    COLOR_GREEN,
    COLOR_PURPLE,
    COLOR_PINK,
    COLOR_CYAN,
    COLOR_RED,
    COLOR_TEAL,
]
